---
title: "Number of regulated proteins per time point"
author: "Marie Locard-Paulet"
date: '`r date()`'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = F)
```

```{r}
require(ggplot2)
require(ggrepel)
require(reshape2)
require(knitr)

colfuncdarkposlight <- colorRampPalette(c("darkred", "red","yellow"))
colfunclightposblue <- colorRampPalette(c("dodgerblue4", "deepskyblue", "greenyellow"))
```

I work with the table output of the statistical analysis:

```{r, echo = T}
Prottab <- read.table("SupTables/ProtfinalStat.txt", header = T, sep = "\t")
```

I remove all the proteins identified with less than 2 unique peptides.

```{r}
Prottab <- Prottab[Prottab$Unique.peptides>=2,]
```

I count the number of regulated protein per couple of time point:

```{r}
mat <- Prottab[!is.na(Prottab$Regulation) & Prottab$Regulation==TRUE,698:712]
matFC <- Prottab[!is.na(Prottab$Regulation) & Prottab$Regulation==TRUE,713:727]
matres <- matrix(ncol = 3, nrow = ncol(mat))
dimnames(matres)[[2]] <- c("TimePoint", "Up", "Down")
lprot <- list()
for (i in 1:ncol(mat)) {
        tp <- dimnames(mat)[[2]][i]
        vecp <- mat[,i]
        vecFC <- matFC[,dimnames(matFC)[[2]]==paste0(tp, ".FC")]
        matres[i,1] <- tp
        matres[i,2] <- length(vecFC[vecFC>=log2(1.75) & vecp <=0.05])
        matres[i,3] <- length(vecFC[vecFC<=-log2(1.75) & vecp <=0.05])
        lprot[[length(lprot)+1]] <- Prottab$psiteID[!is.na(Prottab$Regulation) & Prottab$Regulation==TRUE][abs(vecFC)>=log2(1.75) & vecp <=0.05]
        names(lprot)[length(lprot)] <- tp
}
# Calcul of total number of regualted site per time point:
sites <- Prottab$Majority.protein.IDs[!is.na(Prottab$Regulation) & Prottab$Regulation==TRUE]
mat01 <- mat[,1:5]
mat01[mat01>0.05] <- NA
mat01[!is.na(mat01)] <- 1
vec <- rowSums(mat01)
mat02 <- matFC[,paste0(names(mat[,1:5]), ".FC")]
mat02[abs(mat02)<1] <- NA
mat02[!is.na(mat02)] <- 1
mat02[is.na(mat01) | is.na(mat02)] <- NA
vec2 <- rowSums(mat02)
totalTiO2 <- length(vec2[vec2>0])

gtab <- melt(as.data.frame(matres, stringsAsFactors = F), id.vars = "TimePoint")

tp1 <- sapply(as.character(gtab$TimePoint), function(x) strsplit(x, ".", fixed = T)[[1]][1])
tp2 <- sapply(as.character(gtab$TimePoint), function(x) strsplit(x, ".", fixed = T)[[1]][2])
gtab <- data.frame(gtab, "tp1"=tp1, "tp2"=tp2)
gtab$value <- as.numeric(gtab$value)
gtab$tp1[gtab$TimePoint=="T15.T120"] <- "T120" 
gtab$tp1[gtab$TimePoint=="T30.T120"] <- "T120" 
gtab$tp2[gtab$TimePoint=="T15.T120"] <- "T15" 
gtab$tp2[gtab$TimePoint=="T30.T120"] <- "T30" 
gtab$variable <- as.character(gtab$variable)
gtab$variable[gtab$TimePoint=="T15.T120" & gtab$variable=="Down"] <- "UpR"
gtab$variable[gtab$TimePoint=="T30.T120" & gtab$variable=="Down"] <- "UpR"
gtab$variable[gtab$TimePoint=="T15.T120" & gtab$variable=="Up"] <- "DownR"
gtab$variable[gtab$TimePoint=="T30.T120" & gtab$variable=="Up"] <- "DownR"
gtab$variable[gtab$variable=="DownR"] <- "Down"
gtab$variable[gtab$variable=="UpR"] <- "Up"
gtab$tp1 <- factor(as.character(gtab$tp1), levels = c("T0", "T15", "T30", "T120", "T300", "T600"))
gtab$tp2 <- factor(as.character(gtab$tp2), levels = c("T0", "T15", "T30", "T120", "T300", "T600"))
g1 <- ggplot(subset(gtab, gtab$variable== "Up"), aes(x = tp2, y = tp1, fill = value, label = as.character(value))) + geom_tile() + scale_fill_gradientn(colors = colfuncdarkposlight(100)) + geom_text(size = 7) + theme_minimal() + theme(axis.ticks = element_blank()) + xlab("")
g2 <- ggplot(subset(gtab, gtab$variable== "Down"), aes(x = tp1, y = tp2, fill = value, label = as.character(value))) + geom_tile() + scale_fill_gradientn(colors = colfunclightposblue(100)) + geom_text(size = 7) + theme_minimal()

gtabkeep <- gtab[gtab$tp2=="T0",]
gtabkeep$DataSet <- rep("Proteins", nrow(gtabkeep))

print(g1)
print(g2)
```

# Bar plots:

```{r}
# Barplots:

gtab <- gtabkeep
# Add total values:
gtab$tp1 <- as.character(gtab$tp1)
gtab$tp2 <- as.character(gtab$tp2)
gtab <- rbind(gtab, c("total", "total", totalTiO2, "total", "total", "Proteins")) # , c("total", "total", totalTiO2, "total", "total", "TiO2")

gtab$tp1 <- gsub("T", "", gtab$tp1)
gtab$tp1 <- factor(as.character(gtab$tp1), levels = sort(unique(as.character(gtab$tp1)))[c(6,2,3,1,4,5)])
gtab$value <- as.numeric(gtab$value)

# Calculate the percentage of regulated proteins:
gtab$Percentage <- (gtab$value/nrow(Prottab))*100
g1 <- ggplot(gtab, aes(x = tp1, y = value, fill = variable)) + geom_bar(stat = "identity", position = "stack", col = "black") + facet_wrap(~DataSet, scales = "free") + theme_minimal() + scale_fill_manual(values = c("dodgerblue3", "grey86", "firebrick2")) + ylab("Time point (sec)") + ylab("Number of regulated phosphorylation site")
print(g1)
kable(gtab)

jpeg("Figures/numRegProtBarPlotTime.jpg", 11.69, 8.27, units = "in", res = 300) # width and height in inches.
print(g1)
dev.off()

pdf("Figures/numRegProtBarPlotTime.pdf", useDingbats=FALSE, 11.69, 8.27)
print(g1)
dev.off()
```